version: '3'

services:
  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=db_merge

  app:
    build:
      context: .
    ports:
      - '8080:8080'
    environment:
      - spring.application.name=Merge
      - spring.datasource.url=jdbc:postgresql://db:5432/db_merge
      - spring.datasource.username=postgres
      - spring.datasource.password=123
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
      - spring.datasource.driver-class-name=org.postgresql.Driver
    depends_on:
      - db
